window.CARD_CATALOG = [
  {
    id: 'amex-platinum',
    name: 'Amex Platinum',
    issuer: 'Amex',
    annualFee: 895,
    color: 'bg-zinc-900',
    benefits: [
      { id: 'uber', name: 'Uber Cash', cadence: 'monthly', periodsPerYear: 12, valuePerPeriod: 15, maxAnnualValue: 200, note: '$15/month in Uber Cash plus extra $20 in December (up to $200/year).' },
      { id: 'uberone', name: 'Uber One Membership Credit', cadence: 'yearly', periodsPerYear: 1, valuePerPeriod: 96, maxAnnualValue: 96, note: 'Annual Uber One credit value of $96.' },
      { id: 'subscription', name: 'Streaming / Subscription Credit', cadence: 'monthly', periodsPerYear: 12, valuePerPeriod: 25, maxAnnualValue: 300, note: 'Eligible services include Disney+, Hulu, NYT, WSJ, YouTube Premium/TV and more.' },
      { id: 'hotel', name: 'Fine Hotels + Resorts / THC Credit', cadence: 'semi-annual', periodsPerYear: 2, valuePerPeriod: 150, maxAnnualValue: 300, note: 'Up to $300 total per year across two periods.' },
      { id: 'resy', name: 'Resy Credit', cadence: 'quarterly', periodsPerYear: 4, valuePerPeriod: 100, maxAnnualValue: 400, note: '$100 each quarter.' },
      { id: 'clear', name: 'CLEAR+ Credit', cadence: 'yearly', periodsPerYear: 1, valuePerPeriod: 209, maxAnnualValue: 209, note: 'Up to $209/yr statement credit for CLEAR+ membership.' },
      { id: 'airline', name: 'Airline Incidental Fee Credit', cadence: 'yearly', periodsPerYear: 1, valuePerPeriod: 200, maxAnnualValue: 200, note: 'Incidental airline fees up to $200/yr.' },
      { id: 'lululemon', name: 'Lululemon Credit', cadence: 'quarterly', periodsPerYear: 4, valuePerPeriod: 75, maxAnnualValue: 300, note: '$75 each quarter.' },
      { id: 'walmart', name: 'Walmart+ Membership Credit', cadence: 'monthly', periodsPerYear: 12, valuePerPeriod: 12.95, maxAnnualValue: 155.4, note: 'Up to $12.95 + applicable tax each month.' },
    ],
    earnRates: [
      { id: 'amex-flights', label: 'Flights booked directly or through Amex Travel', multiplier: 5 },
      { id: 'amex-prepaid-hotels', label: 'Prepaid hotels booked on amextravel.com', multiplier: 5 },
      { id: 'amex-other', label: 'All other eligible purchases', multiplier: 1 },
    ],
  },
  {
    id: 'chase-sapphire-reserve',
    name: 'Chase Sapphire Reserve',
    issuer: 'Chase',
    annualFee: 795,
    color: 'bg-sky-700',
    benefits: [
      { id: 'lyft', name: 'Lyft Credit', cadence: 'monthly', periodsPerYear: 12, valuePerPeriod: 10, maxAnnualValue: 120, note: '$10 monthly credit.' },
      { id: 'csr-dd-nonrest-1', name: 'DoorDash Non-Restaurant Credit #1', cadence: 'monthly', periodsPerYear: 12, valuePerPeriod: 10, maxAnnualValue: 120, note: '$10 monthly non-restaurant credit.', group: 'csr-doordash' },
      { id: 'csr-dd-nonrest-2', name: 'DoorDash Non-Restaurant Credit #2', cadence: 'monthly', periodsPerYear: 12, valuePerPeriod: 10, maxAnnualValue: 120, note: '$10 monthly non-restaurant credit.', group: 'csr-doordash' },
      { id: 'csr-dd-restaurant', name: 'DoorDash Restaurant Credit', cadence: 'monthly', periodsPerYear: 12, valuePerPeriod: 5, maxAnnualValue: 60, note: '$5 monthly restaurant credit.', group: 'csr-doordash' },
      { id: 'csr-dashpass', name: 'DashPass Membership Value', cadence: 'yearly', periodsPerYear: 1, valuePerPeriod: 96, maxAnnualValue: 96, note: 'Annual DashPass benefit value of $96.' },
      { id: 'tsa', name: 'TSA PreCheck / Global Entry', cadence: 'yearly', periodsPerYear: 1, valuePerPeriod: 120, maxAnnualValue: 120, cooldownYears: 4, note: 'Up to $85/$120 credit; add last-claim year to enforce 4-year cooldown.' },
      { id: 'peloton', name: 'Peloton Credit', cadence: 'monthly', periodsPerYear: 12, valuePerPeriod: 10, maxAnnualValue: 120, note: '$10 monthly credits.' },
      { id: 'apple-tv', name: 'Apple TV+ Credit', cadence: 'yearly', periodsPerYear: 1, valuePerPeriod: 119.88, maxAnnualValue: 119.88, note: 'Annual value target.' },
      { id: 'apple-music', name: 'Apple Music Credit', cadence: 'yearly', periodsPerYear: 1, valuePerPeriod: 131.88, maxAnnualValue: 131.88, note: 'Annual value target.' },
      { id: 'stubhub', name: 'StubHub / Viagogo Credit', cadence: 'semi-annual', periodsPerYear: 2, valuePerPeriod: 150, maxAnnualValue: 300, note: '$150 each half-year.' },
      { id: 'opentable', name: 'OpenTable Dining Credit', cadence: 'semi-annual', periodsPerYear: 2, valuePerPeriod: 150, maxAnnualValue: 300, note: '$150 each half-year.' },
      { id: 'travel', name: 'Travel Credit', cadence: 'yearly', periodsPerYear: 1, valuePerPeriod: 300, maxAnnualValue: 300, note: '$300 annual travel credit.' },
      { id: 'edit-hotel', name: 'The Edit Hotel Credit', cadence: 'semi-annual', periodsPerYear: 2, valuePerPeriod: 125, maxAnnualValue: 250, note: '$250 yearly split semi-annually.' },
    ],
    earnRates: [
      { id: 'csr-chase-travel', label: 'All purchases through Chase Travel', multiplier: 8 },
      { id: 'csr-flights-direct', label: 'Flights booked direct', multiplier: 4 },
      { id: 'csr-hotels-direct', label: 'Hotels booked direct', multiplier: 4 },
      { id: 'csr-dining', label: 'Dining worldwide', multiplier: 3 },
      { id: 'csr-other', label: 'All other purchases', multiplier: 1 },
    ],
  },
  {
    id: 'capital-one-venture-x',
    name: 'Capital One Venture X',
    issuer: 'Capital One',
    annualFee: 395,
    color: 'bg-emerald-700',
    benefits: [
      { id: 'vx-travel-credit', name: 'C1 Travel Credit', cadence: 'yearly', periodsPerYear: 1, valuePerPeriod: 300, maxAnnualValue: 300, note: '$300 annual travel credit through Capital One Travel.' },
      { id: 'vx-global-entry', name: 'Global Entry / TSA PreCheck Credit', cadence: 'yearly', periodsPerYear: 1, valuePerPeriod: 120, maxAnnualValue: 120, cooldownYears: 4, note: 'Up to $120 credit; add last-claim year to enforce 4-year cooldown.' },
      { id: 'vx-hotel-credit', name: 'Premier / Lifestyle Collection Hotel Credit', cadence: 'per-stay', periodsPerYear: 12, valuePerPeriod: 75, minValuePerPeriod: 50, maxValuePerPeriod: 100, variableValue: true, maxAnnualValue: 1200, note: '$50-$100 per eligible stay; set your per-stay value below.' },
    ],
    earnRates: [
      { id: 'vx-hotels-rental-cars-c1', label: 'Hotels & rental cars through Capital One Travel', multiplier: 10 },
      { id: 'vx-flights-vacation-rentals-c1', label: 'Flights & vacation rentals through Capital One Travel', multiplier: 5 },
      { id: 'vx-other', label: 'Everything else', multiplier: 2 },
    ],
  },
  {
    id: 'amex-gold',
    name: 'Amex Gold',
    issuer: 'Amex',
    annualFee: 325,
    color: 'bg-amber-500',
    benefits: [
      { id: 'gold-uber', name: 'Uber Cash', cadence: 'monthly', periodsPerYear: 12, valuePerPeriod: 10, maxAnnualValue: 120, note: '$10 in Uber Cash each month.' },
      { id: 'gold-dunkin', name: "Dunkin' Credit", cadence: 'monthly', periodsPerYear: 12, valuePerPeriod: 7, maxAnnualValue: 84, note: "$7 monthly statement credit at U.S. Dunkin' locations." },
      { id: 'gold-resy', name: 'Resy Credit', cadence: 'semi-annual', periodsPerYear: 2, valuePerPeriod: 50, maxAnnualValue: 100, note: '$50 statement credits semi-annually.' },
      { id: 'gold-dining', name: 'Select Dining Credit', cadence: 'monthly', periodsPerYear: 12, valuePerPeriod: 10, maxAnnualValue: 120, note: '$10 monthly at eligible partners (Grubhub, Cheesecake Factory, Goldbelly, Wine.com, Five Guys).' },
      { id: 'gold-hotel', name: 'Hotel Credit', cadence: 'yearly', periodsPerYear: 1, valuePerPeriod: 100, maxAnnualValue: 100, note: '$100 credit on eligible 2+ night AmexTravel.com bookings.' },
    ],
    earnRates: [
      { id: 'gold-restaurants', label: 'Restaurants purchases', multiplier: 4 },
      { id: 'gold-us-supermarkets', label: 'U.S. supermarkets purchases', multiplier: 4 },
      { id: 'gold-flights', label: 'Flights booked direct with airlines or AmexTravel.com', multiplier: 3 },
      { id: 'gold-prepaid-hotels-amex', label: 'Prepaid hotels booked on AmexTravel.com', multiplier: 2 },
      { id: 'gold-other-amextravel', label: 'Other eligible purchases booked on AmexTravel.com', multiplier: 2 },
      { id: 'gold-other', label: 'All other eligible purchases', multiplier: 1 },
    ],
  },
  {
    id: 'chase-sapphire-preferred',
    name: 'Chase Sapphire Preferred',
    issuer: 'Chase',
    annualFee: 95,
    color: 'bg-indigo-700',
    benefits: [
      { id: 'csp-hotel', name: 'Hotel Credit', cadence: 'yearly', periodsPerYear: 1, valuePerPeriod: 50, maxAnnualValue: 50, note: '$50 annual hotel credit.' },
      { id: 'csp-doordash', name: 'DoorDash Non-Restaurant Credits', cadence: 'monthly', periodsPerYear: 12, valuePerPeriod: 10, maxAnnualValue: 120, note: '$10 monthly non-restaurant credits.' },
      { id: 'csp-dashpass', name: 'DashPass Membership Value', cadence: 'yearly', periodsPerYear: 1, valuePerPeriod: 96, maxAnnualValue: 96, note: 'Annual DashPass benefit value of $96.' },
    ],
    earnRates: [
      { id: 'csp-chase-travel', label: 'Travel purchased through Chase Travel', multiplier: 5 },
      { id: 'csp-dining', label: 'Dining + eligible delivery services', multiplier: 3 },
      { id: 'csp-online-grocery', label: 'Online grocery (excluding Target, Walmart, wholesale clubs)', multiplier: 3 },
      { id: 'csp-streaming', label: 'Select streaming services', multiplier: 3 },
      { id: 'csp-other-travel', label: 'Other travel purchases', multiplier: 2 },
      { id: 'csp-other', label: 'All other eligible purchases', multiplier: 1 },
    ],
  },
];
